version: '3'
services:
  dataiq-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-dataiq-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_dataiq_api:/usr/lib/python3.6/site-packages/vlab_dataiq_api
    command: ["python3", "app.py"]

  dataiq-worker:
    image:
      willnx/vlab-dataiq-worker
    volumes:
      - ./vlab_dataiq_api:/usr/lib/python3.6/site-packages/vlab_dataiq_api
      - /mnt/raid/images/dataiq:/images:ro
    environment:
      - INF_VCENTER_SERVER=my-vcenter.local
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=ChangeMe
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  dataiq-broker:
    image:
      rabbitmq:3.7-alpine
